name: clean_news_ai
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  equatable:
    git:
      url: git://github.com/Renesanse/equatable.git

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http:
  intl:
  share:
  uuid:
  webview_flutter:
  worker_manager:
  flutter_bloc:
  built_redux: ^7.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
