name: clean_news_ai
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  intl: ^0.15.7
  share: ^0.5.3
  uuid: ^2.0.0
  shared_preferences: ^0.4.3
  pull_to_refresh: ^1.2.0
  launch_review: ^1.0.1
  cloud_firestore: ^0.9.7
  webview_flutter: ^0.3.5
  flutter_screenutil: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
